
from __future__ import annotations
from datetime import date
from typing import List, Optional
from pydantic import BaseModel, Field, field_validator
import re


# ═══════════════════════════════════════════════════════════════════════════════
#  AUTH
# ═══════════════════════════════════════════════════════════════════════════════

class LoginRequest(BaseModel):
    uid: str = Field(..., min_length=3, max_length=36, description="Patient's Unique ID")
    dob: str = Field(..., description="Date of Birth in YYYY-MM-DD format")

    @field_validator("dob")
    @classmethod
    def validate_dob_format(cls, v: str) -> str:
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", v):
            raise ValueError("dob must be in YYYY-MM-DD format")
        return v


class LoginResponse(BaseModel):
    success: bool
    message: str
    access_token: Optional[str] = None
    patient: Optional[PatientInfo] = None


class PatientInfo(BaseModel):
    uid: str
    full_name: str
    gender: str


# ═══════════════════════════════════════════════════════════════════════════════
#  VISITS
# ═══════════════════════════════════════════════════════════════════════════════

class Medicine(BaseModel):
    name: str = Field(..., description="Drug / medicine name")
    dosage: str = Field(..., description="e.g. '500 mg twice daily'")
    duration: str = Field(..., description="e.g. '7 days'")

    # Used when building the Membrain memory node
    def to_text(self) -> str:
        return f"{self.name} — {self.dosage} for {self.duration}"


class SaveVisitRequest(BaseModel):
    patient_uid: str
    visit_date: date = Field(default_factory=date.today)
    symptoms: str = Field(..., min_length=2, description="Patient-reported symptoms")
    diagnosis: str = Field(..., min_length=2, description="Doctor's diagnosis")
    medicines: List[Medicine] = Field(default_factory=list)
    precautions: Optional[str] = None
    attending_doctor: Optional[str] = None
    is_allergy_visit: bool = Field(
        default=False,
        description="Set True if this visit involves a new allergy discovery"
    )
    new_allergen: Optional[str] = Field(
        default=None,
        description="If is_allergy_visit=True, name of the allergen"
    )
    allergen_severity: Optional[str] = Field(
        default="moderate",
        description="mild | moderate | severe | life-threatening"
    )


class SaveVisitResponse(BaseModel):
    success: bool
    visit_id: Optional[int] = None
    membrain_node_id: Optional[str] = None
    message: str


# ═══════════════════════════════════════════════════════════════════════════════
#  SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

class SummaryRequest(BaseModel):
    patient_uid: str
    context_hint: Optional[str] = Field(
        default=None,
        description="Current complaint or reason for visit — helps Gemini focus the summary"
    )


class SummaryResponse(BaseModel):
    success: bool
    patient_uid: str
    briefing: str = Field(description="3-sentence Doctor's Briefing generated by Gemini")
    memories_retrieved: int = Field(description="Number of Membrain memory nodes used")
    message: str = "OK"


# ═══════════════════════════════════════════════════════════════════════════════
#  CONFLICT CHECK
# ═══════════════════════════════════════════════════════════════════════════════

class ConflictCheckRequest(BaseModel):
    patient_uid: str
    proposed_medicines: List[Medicine] = Field(
        ..., description="The new drugs the doctor intends to prescribe"
    )
    proposed_diagnosis: Optional[str] = None


class ConflictDetail(BaseModel):
    conflict_type: str              # 'allergy' | 'drug_interaction' | 'contraindication'
    severity: str                   # 'critical' | 'warning' | 'info'
    description: str
    source_memory_id: str           # Membrain node that flagged this
    recommendation: str


class ConflictCheckResponse(BaseModel):
    success: bool
    patient_uid: str
    has_conflicts: bool
    conflicts: List[ConflictDetail] = Field(default_factory=list)
    ai_summary: Optional[str] = None   # Gemini one-liner summary of all conflicts
    message: str = "OK"


# Forward-reference resolution for LoginResponse
LoginResponse.model_rebuild()